DROP TABLE IF EXISTS Kayttaja CASCADE;
DROP TABLE IF EXISTS Resepti CASCADE;
DROP TABLE IF EXISTS Suosikit CASCADE;
DROP TABLE IF EXISTS Ainekset CASCADE;
DROP TABLE IF EXISTS Raaka_aineet CASCADE;
DROP TABLE IF EXISTS Ravintoarvot CASCADE;
DROP TABLE IF EXISTS Yksikot CASCADE;
DROP TABLE IF EXISTS Yksikko_muunnokset CASCADE;
